/*
 * FINBOURNE Honeycomb Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.42
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.luminesce.model;

import com.finbourne.luminesce.model.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BackgroundQueryResponse
 */
public class BackgroundQueryResponseTest {
    private final BackgroundQueryResponse model = new BackgroundQueryResponse();

    /**
     * Model tests for BackgroundQueryResponse
     */
    @Test
    public void testBackgroundQueryResponse() {
        // TODO: test BackgroundQueryResponse
    }

    /**
     * Test the property 'executionId'
     */
    @Test
    public void executionIdTest() {
        // TODO: test executionId
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'cancel'
     */
    @Test
    public void cancelTest() {
        // TODO: test cancel
    }

    /**
     * Test the property 'fetchJson'
     */
    @Test
    public void fetchJsonTest() {
        // TODO: test fetchJson
    }

    /**
     * Test the property 'fetchJsonProper'
     */
    @Test
    public void fetchJsonProperTest() {
        // TODO: test fetchJsonProper
    }

    /**
     * Test the property 'fetchCsv'
     */
    @Test
    public void fetchCsvTest() {
        // TODO: test fetchCsv
    }

    /**
     * Test the property 'fetchPipe'
     */
    @Test
    public void fetchPipeTest() {
        // TODO: test fetchPipe
    }

    /**
     * Test the property 'fetchExcel'
     */
    @Test
    public void fetchExcelTest() {
        // TODO: test fetchExcel
    }

    /**
     * Test the property 'fetchSqlite'
     */
    @Test
    public void fetchSqliteTest() {
        // TODO: test fetchSqlite
    }

    /**
     * Test the property 'histogram'
     */
    @Test
    public void histogramTest() {
        // TODO: test histogram
    }

}
