/*
 * FINBOURNE Honeycomb Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.42
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.luminesce.model;

import com.finbourne.luminesce.model.BackgroundQueryState;
import com.finbourne.luminesce.model.Column;
import com.finbourne.luminesce.model.FeedbackEventArgs;
import com.finbourne.luminesce.model.TaskStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BackgroundQueryProgressResponse
 */
public class BackgroundQueryProgressResponseTest {
    private final BackgroundQueryProgressResponse model = new BackgroundQueryProgressResponse();

    /**
     * Model tests for BackgroundQueryProgressResponse
     */
    @Test
    public void testBackgroundQueryProgressResponse() {
        // TODO: test BackgroundQueryProgressResponse
    }

    /**
     * Test the property 'hasData'
     */
    @Test
    public void hasDataTest() {
        // TODO: test hasData
    }

    /**
     * Test the property 'rowCount'
     */
    @Test
    public void rowCountTest() {
        // TODO: test rowCount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'feedback'
     */
    @Test
    public void feedbackTest() {
        // TODO: test feedback
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'queryName'
     */
    @Test
    public void queryNameTest() {
        // TODO: test queryName
    }

    /**
     * Test the property 'columnsAvailable'
     */
    @Test
    public void columnsAvailableTest() {
        // TODO: test columnsAvailable
    }

}
