/*
 * FINBOURNE Honeycomb Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.42
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.luminesce.model;

import com.finbourne.luminesce.model.BackgroundQueryState;
import com.finbourne.luminesce.model.TaskStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BackgroundQueryCancelResponse
 */
public class BackgroundQueryCancelResponseTest {
    private final BackgroundQueryCancelResponse model = new BackgroundQueryCancelResponse();

    /**
     * Model tests for BackgroundQueryCancelResponse
     */
    @Test
    public void testBackgroundQueryCancelResponse() {
        // TODO: test BackgroundQueryCancelResponse
    }

    /**
     * Test the property 'hadData'
     */
    @Test
    public void hadDataTest() {
        // TODO: test hadData
    }

    /**
     * Test the property 'previousStatus'
     */
    @Test
    public void previousStatusTest() {
        // TODO: test previousStatus
    }

    /**
     * Test the property 'previousState'
     */
    @Test
    public void previousStateTest() {
        // TODO: test previousState
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

}
