/*
 * FINBOURNE Honeycomb Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.42
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.luminesce.model;

import com.finbourne.luminesce.model.ConditionAttributes;
import com.finbourne.luminesce.model.DataType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Column
 */
public class ColumnTest {
    private final Column model = new Column();

    /**
     * Model tests for Column
     */
    @Test
    public void testColumn() {
        // TODO: test Column
    }

    /**
     * Test the property 'isPrimaryKey'
     */
    @Test
    public void isPrimaryKeyTest() {
        // TODO: test isPrimaryKey
    }

    /**
     * Test the property 'isMain'
     */
    @Test
    public void isMainTest() {
        // TODO: test isMain
    }

    /**
     * Test the property 'isRequiredByProvider'
     */
    @Test
    public void isRequiredByProviderTest() {
        // TODO: test isRequiredByProvider
    }

    /**
     * Test the property 'clientIds'
     */
    @Test
    public void clientIdsTest() {
        // TODO: test clientIds
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'conditionUsage'
     */
    @Test
    public void conditionUsageTest() {
        // TODO: test conditionUsage
    }

    /**
     * Test the property 'sampleValues'
     */
    @Test
    public void sampleValuesTest() {
        // TODO: test sampleValues
    }

    /**
     * Test the property 'allowedValues'
     */
    @Test
    public void allowedValuesTest() {
        // TODO: test allowedValues
    }

}
