/*
 * FINBOURNE Honeycomb Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.42
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.luminesce.model;

import com.finbourne.luminesce.model.FeedbackLevel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FeedbackEventArgs
 */
public class FeedbackEventArgsTest {
    private final FeedbackEventArgs model = new FeedbackEventArgs();

    /**
     * Model tests for FeedbackEventArgs
     */
    @Test
    public void testFeedbackEventArgs() {
        // TODO: test FeedbackEventArgs
    }

    /**
     * Test the property 'when'
     */
    @Test
    public void whenTest() {
        // TODO: test when
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'executionId'
     */
    @Test
    public void executionIdTest() {
        // TODO: test executionId
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

    /**
     * Test the property 'stateId'
     */
    @Test
    public void stateIdTest() {
        // TODO: test stateId
    }

    /**
     * Test the property 'messageTemplate'
     */
    @Test
    public void messageTemplateTest() {
        // TODO: test messageTemplate
    }

    /**
     * Test the property 'propertyValues'
     */
    @Test
    public void propertyValuesTest() {
        // TODO: test propertyValues
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
